"""update user db schema

Revision ID: 01a70b7a5fbe
Revises: 1a31ce608336
Create Date: 2025-07-04 16:19:38.187634

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '01a70b7a5fbe'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('user', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False))
    op.add_column('user', sa.Column('native_language', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('user', sa.Column('purpose_language', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.add_column('user', sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('teacher', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('current_lesson', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('extra_minute', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('membership', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_column('user', 'membership')
    op.drop_column('user', 'extra_minute')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'current_lesson')
    op.drop_column('user', 'teacher')
    op.drop_column('user', 'time')
    op.drop_column('user', 'reason')
    op.drop_column('user', 'purpose_language')
    op.drop_column('user', 'native_language')
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
