"""change hashed password as nullable

Revision ID: 68803e34852a
Revises: 1d8789141687
Create Date: 2025-07-07 11:48:20.575321

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '68803e34852a'
down_revision = '1d8789141687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
